name: Deploy Website

on:
  push:
    branches:
      - master  # hoặc branch bạn muốn deploy
permissions:
  contents: write  # cấp quyền push
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # nếu file index.html ở root repo
